module.exports = [
{
  "pNo": 0,
  "pName": "单位基本信息",
  "afamily": ['个体工农商户','电商服务点','工农商企业'],
  "pSuccess": [
    {inclose:true, gname:"indType", p:'主营业务', t:"industrytype", apdclist:require('../libs/apd1.js'), apdvalue:[0, 0, 0] },
    {gname:"uName", p:'单位简称',t:"d2" },
    {gname: "nick", p: '单位简介', t: "d2"},
    {gname: "thumbnail", p: '图片简介', t: "thumb" },
    {gname: "address", p: '注册地', t: "ed"},
    {gname: "licenseNumber", p:'社会信用代码', t: "h3" }
  ],
  "puRoles": [],
  "pBewrite": "单位负责人提出岗位和单位设置或修改申请,提交单位或个人身份证明文件的照片,由电子商务服务公司进行审批。",
  "suRoles": [
    "32",
    "31"
  ],
  "pModle": "unitInfo"
},
{
  "pNo": 1,
  "pName": "单位实际控制人、股东、管理层变动",
  "afamily": ['实际控制人','股东','管理层'],
  "pSuccess": [
    {gname:"reportPeriod", p:'报告期',t:"rdate"},
    {gname: "address", p: '详细地址', t: "ed"},
    {gname: "licenseNumber", p:'社会信用代码', t: "h3" }
  ],
  "puRoles": [],
  "pBewrite": "单位负责人提出岗位和单位设置或修改申请,提交单位或个人身份证明文件的照片,由电子商务服务公司进行审批。",
  "suRoles": [
    "32",
    "31"
  ],
  "pModle": "unitRegistration"
},
{
  "pNo": 2,
  "pName": "资产负债表",
  "pSuccess": [
    {gname:"reportPeriod", p:'报告期',t:"rdate"},
    { gname: "b1", p: "货币资金", t: "d2" },
    { gname: "b2", p: "短期投资", t: "d2" },
    { gname: "b3", p: "应收票据", t: "d2" },
    { gname: "b4", p: "应收账款", t: "d2" },
    { gname: "b5", p: "预付账款", t: "d2" },
    { gname: "b6", p: "应收股利", t: "d2" },
    { gname: "b7", p: "应收利息", t: "d2" },
    { gname: "b8", p: "其他应收款", t: "d2" },
    { gname: "b9", p: "存货", t: "d2" },
    { gname: "b10", p: "其中：原材料", t: "d2" },
    { gname: "b11", p: "在产品", t: "d2" },
    { gname: "b12", p: "库存商品", t: "d2" },
    { gname: "b13", p: "周转材料", t: "d2" },
    { gname: "b14", p: "其他流动资产", t: "d2" },
    { gname: "b15", p: "流动资产合计", t: "d2" },
    { gname: "b16", p: "长期债券投资", t: "d2" },
    { gname: "b17", p: "长期股权投资", t: "d2" },
    { gname: "b18", p: "固定资产", t: "d2" },
    { gname: "b19", p: "减：累计折旧", t: "d2" },
    { gname: "b20", p: "固定资产账面价值", t: "d2" },
    { gname: "b21", p: "在建工程", t: "d2" },
    { gname: "b22", p: "工程物资", t: "d2" },
    { gname: "b23", p: "固定资产清理", t: "d2" },
    { gname: "b24", p: "生产性生物资产", t: "d2" },
    { gname: "b25", p: "无形资产", t: "d2" },
    { gname: "b26", p: "开发支出", t: "d2" },
    { gname: "b27", p: "长期待摊费用", t: "d2" },
    { gname: "b28", p: "其他非流动资产", t: "d2" },
    { gname: "b29", p: "非流动资产合计", t: "d2" },
    { gname: "b30", p: "资产总计", t: "d2" },
    { gname: "b31", p: "短期借款", t: "d2" },
    { gname: "b32", p: "应付票据", t: "d2" },
    { gname: "b33", p: "应付账款", t: "d2" },
    { gname: "b34", p: "预收账款", t: "d2" },
    { gname: "b35", p: "应付职工薪酬", t: "d2" },
    { gname: "b36", p: "应交税费", t: "d2" },
    { gname: "b37", p: "应付利息", t: "d2" },
    { gname: "b38", p: "应付利润", t: "d2" },
    { gname: "b39", p: "其他应付款", t: "d2" },
    { gname: "b40", p: "其他流动负债", t: "d2" },
    { gname: "b41", p: "流动负债合计", t: "d2" },
    { gname: "b42", p: "长期借款", t: "d2" },
    { gname: "b43", p: "长期应付款", t: "d2" },
    { gname: "b44", p: "递延收益", t: "d2" },
    { gname: "b45", p: "其他非流动负债", t: "d2" },
    { gname: "b46", p: "非流动负债合计", t: "d2" },
    { gname: "b47", p: "负债合计", t: "d2" },
    { gname: "b48", p: "实收资本", t: "d2" },
    { gname: "b49", p: "资本公积", t: "d2" },
    { gname: "b50", p: "盈余公积", t: "d2" },
    { gname: "b51", p: "未分配利润", t: "d2" },
    { gname: "b52", p: "所有者权益（或股东权益）合计", t: "d2" },
    { gname: "b53", p: "负债和所有者权益（或股东权益）总计", t: "d2" }
  ],
  "puRoles": [
    "20",
    "admin"
  ],
  "pBewrite": "编写各类文章,经单位领导审批后发布。个人编写的此类文章由所属服务机构审批。",
  "suRoles": [
    "21",
    "20"
  ],
  "pModle": "quarterlyReports"
},
{
  "pNo": 3,
  "pName": "利润表",
  "pSuccess": [
    {gname: "uName", p:'名称', t:"h3" },
    { gname: "b1", p: "一、营业收入", t: "d2" },
    { gname: "b2", p: "减：营业成本", t: "d2" },
    { gname: "b3", p: "营业税金及附加", t: "d2" },
    { gname: "b4", p: "其中：消费税", t: "d2" },
    { gname: "b5", p: "营业税", t: "d2" },
    { gname: "b6", p: "城市维护建设税", t: "d2" },
    { gname: "b7", p: "资源税", t: "d2" },
    { gname: "b8", p: "土地增值税", t: "d2" },
    { gname: "b9", p: "城镇土地使用税、房产税、车船税、印花税", t: "d2" },
    { gname: "b10", p: "教育费附加、矿产资源补偿费、排污费", t: "d2" },
    { gname: "b11", p: "销售费用", t: "d2" },
    { gname: "b12", p: "其中：商品维修费", t: "d2" },
    { gname: "b13", p: "广告费和业务宣传费", t: "d2" },
    { gname: "b14", p: "管理费用", t: "d2" },
    { gname: "b15", p: "其中：开办费", t: "d2" },
    { gname: "b16", p: "业务招待费", t: "d2" },
    { gname: "b17", p: "研究费用", t: "d2" },
    { gname: "b18", p: "财务费用", t: "d2" },
    { gname: "b19", p: "其中：利息费用（收入以“-”号填列）", t: "d2" },
    { gname: "b20", p: "加：投资收益（损失以“-”号填列）", t: "d2" },
    { gname: "b21", p: "二、营业利润（亏损以“-”号填列）", t: "d2" },
    { gname: "b22", p: "加：营业外收入", t: "d2" },
    { gname: "b23", p: "其中：政府补助", t: "d2" },
    { gname: "b24", p: "减：营业外支出", t: "d2" },
    { gname: "b25", p: "其中：坏账损失", t: "d2" },
    { gname: "b26", p: "无法收回的长期债券投资损失", t: "d2" },
    { gname: "b27", p: "无法收回的长期股权投资损失", t: "d2" },
    { gname: "b28", p: "自然灾害等不可抗力因素造成的损失", t: "d2" },
    { gname: "b29", p: "税收滞纳金", t: "d2" },
    { gname: "b30", p: "三、利润总额（亏损总额以“-”号填列）", t: "d2" },
    { gname: "b31", p: "减：所得税费用", t: "d2" },
    { gname: "b32", p: "四、净利润（净亏损以“-”号填列）", t: "d2" }
  ],
  "pBewrite": "产品条线提出产品设置或修改申请,由产品条线负责人进行审批。",
  "puRoles": [
    "12",
    "11"
  ],
  "sFinallyRole": "12",
  "pModle": "profitReports"
}
]
